
import type { Car } from '@/types';

// Этот массив теперь используется только как пример данных или для первоначального заполнения базы данных.
// Реальные данные будут загружаться из Firestore.
export const initialCarsData: Car[] = [
  {
    id: '1', 
    make: 'Toyota',
    model: 'Camry',
    year: 2023,
    price: 28000,
    horsepower: 203,
    mpg: 32,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'sedan silver',
    features: ['Sunroof', 'Lane Assist'],
  },
  {
    id: '2',
    make: 'Honda',
    model: 'CR-V',
    year: 2024,
    price: 32000,
    horsepower: 190,
    mpg: 30,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'suv blue',
    features: ['All-Wheel Drive', 'Apple CarPlay'],
  },
  {
    id: '3',
    make: 'Ford',
    model: 'F-150',
    year: 2023,
    price: 45000,
    horsepower: 400,
    mpg: 20,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'pickup truck',
    features: ['Towing Package', 'Large Touchscreen'],
  },
  {
    id: '4',
    make: 'Tesla',
    model: 'Model 3',
    year: 2024,
    price: 42000,
    horsepower: 283,
    mpg: 132, // MPGe
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'electric car',
    features: ['Autopilot', 'Panoramic Roof'],
  },
  {
    id: '5',
    make: 'BMW',
    model: 'X5',
    year: 2023,
    price: 65000,
    horsepower: 335,
    mpg: 25,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'luxury suv',
    features: ['Leather Seats', 'Harman Kardon Sound'],
  },
  {
    id: '6',
    make: 'Chevrolet',
    model: 'Silverado',
    year: 2022,
    price: 40000,
    horsepower: 355,
    mpg: 18,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'truck red',
    features: ['Off-road Package', 'Heated Seats'],
  },
  {
    id: '7',
    make: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2024,
    price: 50000,
    horsepower: 255,
    mpg: 29,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'luxury sedan',
    features: ['Ambient Lighting', 'Burmester Audio'],
  },
  {
    id: '8',
    make: 'Audi',
    model: 'Q5',
    year: 2023,
    price: 48000,
    horsepower: 261,
    mpg: 26,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'compact suv',
    features: ['Virtual Cockpit', 'Quattro AWD'],
  },
  {
    id: '9',
    make: 'Volkswagen',
    model: 'Golf',
    year: 2023,
    price: 25000,
    horsepower: 147,
    mpg: 34,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'hatchback white',
    features: ['Digital Cockpit', 'Adaptive Cruise Control'],
  },
  {
    id: '10',
    make: 'Hyundai',
    model: 'Tucson',
    year: 2024,
    price: 29000,
    horsepower: 187,
    mpg: 28,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'suv gray',
    features: ['Wireless CarPlay', 'Blind-Spot Assist'],
  },
  {
    id: '11',
    make: 'Kia',
    model: 'Sportage',
    year: 2024,
    price: 28500,
    horsepower: 187,
    mpg: 28,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'suv black',
    features: ['Panoramic Sunroof', 'Highway Driving Assist'],
  },
  {
    id: '12',
    make: 'Nissan',
    model: 'Rogue',
    year: 2023,
    price: 30000,
    horsepower: 201,
    mpg: 33,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'crossover red',
    features: ['ProPILOT Assist', 'Divide-N-Hide Cargo'],
  },
  {
    id: '13',
    make: 'Mazda',
    model: 'CX-5',
    year: 2023,
    price: 31000,
    horsepower: 187,
    mpg: 28,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'suv soulred',
    features: ['i-Activ AWD', 'Bose Audio'],
  },
  {
    id: '14',
    make: 'Subaru',
    model: 'Outback',
    year: 2024,
    price: 33000,
    horsepower: 182,
    mpg: 29,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'wagon green',
    features: ['Symmetrical AWD', 'EyeSight Driver Assist'],
  },
  {
    id: '15',
    make: 'Volvo',
    model: 'XC60',
    year: 2023,
    price: 48000,
    horsepower: 247,
    mpg: 25,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'luxury suv white',
    features: ['Google Built-in', 'Pilot Assist'],
  },
  {
    id: '16',
    make: 'Lexus',
    model: 'RX 350',
    year: 2024,
    price: 55000,
    horsepower: 275,
    mpg: 25,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'luxury crossover',
    features: ['Mark Levinson Audio', 'Lexus Safety System+ 3.0'],
  },
  {
    id: '17',
    make: 'Porsche',
    model: '911 Carrera',
    year: 2024,
    price: 115000,
    horsepower: 379,
    mpg: 20,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'sports car silver',
    features: ['PASM', 'Sport Chrono Package'],
  },
  {
    id: '18',
    make: 'Jaguar',
    model: 'F-PACE',
    year: 2023,
    price: 58000,
    horsepower: 246,
    mpg: 24,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'luxury suv dynamic',
    features: ['Pivi Pro Infotainment', 'Meridian Sound System'],
  },
  {
    id: '19',
    make: 'Land Rover',
    model: 'Defender 110',
    year: 2024,
    price: 65000,
    horsepower: 296,
    mpg: 19,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'offroad suv',
    features: ['Terrain Response 2', '3D Surround Camera'],
  },
  {
    id: '20',
    make: 'BMW',
    model: '3 Series',
    year: 2024,
    price: 48000,
    horsepower: 255,
    mpg: 29,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'sedan sport',
    features: ['Live Cockpit Pro', 'Driving Assistance Package'],
  }
];

// carMakes теперь будет динамически генерироваться на основе данных из Firestore в CatalogPage.
// export const carMakes = Array.from(new Set(cars.map(car => car.make))).sort();
